# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  script:
        - git remote show writable || git remote add writable https://JCH:c5c3ce3d31b12cddc2ff785f44032719da657461@github.com/Youchama/repo2.git
        - git checkout main
        - git push writable main
  only:
        - main      
