# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags: -*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git remote add repo2 "https://JCH:${{ secrets.KEY }}@github.com/Youchama/repo2.git"
          git remote add repo1 "https://JCH:${{ secrets.KEY }}@github.com/Youchama/repo1.git"
          echo "Ajout du repo ok"
          git fetch repo1
          git checkout -b coucou repo1/main
          echo "Checkout ok"
          git fetch repo2
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          echo "ça push mon pot"
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
